name: Extract and Load Credit Data

env:
  SSH_PRIVATE_KEY: ${{secrets.SECRET_TOKEN}}
  ENVIRONMENT_BASE64: ${{secrets.ENV_FILE}}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8 AM
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Decode Google Credentials
        run: echo "$ENVIRONMENT_BASE64" | base64 --decode > .env

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -L 6667:ars-rapid-prod-db.cmyqyq1ypwcc.eu-west-1.rds.amazonaws.com:5432 ubuntu@bastion.onemedtest.com

      - name: Run Pipeline Script
        run: python generate_report.py

      - name: Send Slack Notification
        uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#helium-data-engineering'
        if: always()
